url: https://www.laqueza-construction.com
baseurl: 

# Site settings
title: LaQueza Construction
email: laquezaconstruction@gmail.com
description: "LaQueza Construction. A proud tradition of services as General Contractor with more than 30 years of experience. LaQueza Construction base in Philippines compose of famiy members that has passion in building homes with highest quality."


# Team names, titles and social links
people:
- name: Engr. Cipriano C. Gagan
  pic: 1
  position: CEO / President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Engr. Glen Claudius A. Gagan
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Engr. Jeris Bryan A. Gagan
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty